cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - worker/target

stages:
  - compile
  - deploy

build_bin:
  stage: compile
  image: rust:1.58.1-buster
  tags:
    - ubuntu
  artifacts:
    paths:
      - worker/target/release/worker
  script:
    - cd worker
    - cargo build --release

deploy_image:
  stage: deploy
  tags:
    - docker
  dependencies:
    - build_bin
  script:
    - cd worker
    - docker build -t registry.anspar.io/anspar_ipfs:latest .
    - docker login -u "$DOCKER_L" -p "$DOCKER_P" registry.anspar.io
    - docker push registry.anspar.io/anspar_ipfs:latest