stages:
  - compile
  - build
  - deploy


build_bin:
  stage: compile
  image: rust:1.58.1-buster
  tags:
    - ubuntu
  artifacts:
    paths:
      - worker/target/release/worker
  script:
    - cd worker
    - cargo build --release

build_image:
  stage: build
  tags:
    - docker
  dependencies:
    - build_bin
  script:
    - ls -l worker/target/release/worker
    - cd worker
    - docker build -t registry.anspar.io/anspar_ipfs:latest .

deploy_image:
  stage: deploy
  tags:
    - docker
  dependencies:
    - build_image
  script:
    - echo "$DOCKER_L"
    - docker login -u "$DOCKER_L" -p "$DOCKER_P" registry.anspar.io
    - docker push registry.anspar.io/anspar_ipfs:latest