stages:
  - compile
  - build
  - deploy


build_bin:
  stage: compile
  image: rust:1.57.0-buster
  tags:
    - ubuntu
  artifacts:
    paths:
      - worker/target/release/worker
  script:
    - cd worker
    - cargo build --release

build_image:
  stage: build
  tags:
    - docker
  dependencies:
    - build_bin
  script:
    - ls -l worker/target/release/worker
